#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

RELEASE_STRATEGY="patch"

if [ ! -z "$1" ]; then
  RELEASE_STRATEGY="$1"
  shift
fi

function printHelp(){
   >&2 echo "Usage: $(basename "$0") [patch|minor|major]"
}

function currentVersion() {
  echo $(${SCRIPT_DIR}/gradlew properties -q | awk '/^version:/ {print $2}')
}

increment_version() {
  local delimiter=.
  local array=($(echo "$1" | tr $delimiter '\n'))
  array[$2]=$((array[$2]+1))
  echo $(local IFS=$delimiter ; echo "${array[*]}")
}

shopt -s extglob
case "$RELEASE_STRATEGY" in
      "--help" | "-?" )
        printHelp
      ;;
      "patch" )
        # Nothing to do
      ;;
      "minor" )
        CURRENT_VERSION=$(currentVersion)
        RELEASE_VERSION=$(increment_version ${CURRENT_VERSION} 1)
      ;;
      "major" )
        CURRENT_VERSION=$(currentVersion)
        RELEASE_VERSION=$(increment_version ${CURRENT_VERSION} 0)
      ;;
      +([0-9])?(.+([0-9]))?(.+([0-9])) )
        RELEASE_VERSION="$RELEASE_STRATEGY-SNAPSHOT"
      ;;
      *)
        printHelp
      ;;
esac

if [ ! -z "${RELEASE_VERSION}" ]; then
  ${SCRIPT_DIR}/gradlew :updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=${RELEASE_VERSION}
fi

exec ./gradlew -Prelease.useAutomaticVersion=true "$@"